<a href="https://colab.research.google.com/github/Moisito12/Tensorflow-2.0/blob/master/3_1_Constantes%2C_Variables_y_Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Constantes, Variables y Tensores**

In [2]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 42kB/s 
     |████████████████████████████████| 419kB 41.5MB/s 
     |████████████████████████████████| 3.0MB 37.5MB/s 


# Cómo crear una constante

In [0]:
import tensorflow as tf
import numpy as np

In [5]:
tf.__version__

'2.0.0-alpha0'

In [0]:
#Definir una constante en tensorflow
tensor_20 = tf.constant([[23,4],[32,51]])

In [7]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [8]:
#Obtener el tamaño de un tensor
tensor_20.shape

TensorShape([2, 2])

# Consultar los valores de una constante

In [10]:
#Obtener los valores directamente desde una constante de Tensorflow con numpy, sin necesidad de una sesión
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
#Podemos convertir una array de numpy a un tensor de Tensorflow directamente
numpy_tensor = np.array([[23,4],[32,51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [13]:
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

# Variables

Definir una variable

In [15]:
tf2_variable = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

Consultar los valores de una variable

In [16]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

Cambiar el valor especifíco de una variable

In [17]:
tf2_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [18]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

Operaciones con Tensores

In [19]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: id=34, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>