<a href="https://colab.research.google.com/github/Moisito12/Tensorflow-2.0/blob/master/3_1_Constantes%2C_Variables_y_Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Constantes, Variables y Tensores**

In [2]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 42kB/s 
     |████████████████████████████████| 419kB 41.5MB/s 
     |████████████████████████████████| 3.0MB 37.5MB/s 


# Cómo crear una constante

In [0]:
import tensorflow as tf
import numpy as np

In [5]:
tf.__version__

'2.0.0-alpha0'

In [0]:
#Definir una constante en tensorflow
tensor_20 = tf.constant([[23,4],[32,51]])

In [7]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [8]:
#Obtener el tamaño de un tensor
tensor_20.shape

TensorShape([2, 2])

# Consultar los valores de una constante

In [10]:
#Obtener los valores directamente desde una constante de Tensorflow con numpy, sin necesidad de una sesión
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
#Podemos convertir una array de numpy a un tensor de Tensorflow directamente
numpy_tensor = np.array([[23,4],[32,51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [13]:
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

# Variables

Definir una variable

In [15]:
tf2_variable = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

Consultar los valores de una variable

In [16]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

Cambiar el valor especifíco de una variable

In [17]:
tf2_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [18]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

Operaciones con Tensores

In [19]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: id=34, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

Sumar un escalar a un tensor

In [20]:
tensor *2

<tf.Tensor: id=37, shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

Multiplicar un escalar a un tensor

In [21]:
tensor * 5

<tf.Tensor: id=40, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

Utilizar funciones de Numpy sobre tensores en Tensorflow

In [23]:
#Obtener todos los cuadrados de todos los números de un tensor de Tensorflow
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [25]:
#Obtener todos la raíz cuadrada de todos los números de un tensor de Tensorflow
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

Producto a escalar entre dos tensores

In [26]:
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

# Strings con Tensorflow 2.0

In [27]:
tf_string = tf.constant("Tensorflow")
tf_string

<tf.Tensor: id=49, shape=(), dtype=string, numpy=b'Tensorflow'>

# Operaciones simples con strings

In [28]:
tf.strings.length(tf_string)

<tf.Tensor: id=51, shape=(), dtype=int32, numpy=10>

In [29]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=56, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

# Almacenar arrays de strings en tensorflow

In [0]:
tf_string_array = tf.constant(["Tensorflow","Deep Learning", "IA"])

In [31]:
#Iterar sobre un array de strings en TensorFlow
for string in tf_string_array:
  print(string)

tf.Tensor(b'Tensorflow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'IA', shape=(), dtype=string)
